### ISSUE TITLE
About branches: only master?

### ISSUE THREAD

**Issue by brunolemos** [ebrian/gitdummy#23] opened 2015-09-14 00:41 UTC
How to make it do it for all branches?

**Comment by ebrian** [comment] 2015-09-14 12:31
This was a proposed feature a while back. Reason it was never implemented is because GitHub does not recognize non-master contributions for the contribution log, so it's a little more complicated than just using the same method on each branch as GitDummy does on the master branch. Therefore, this would required consolidating all branches from the target repo into the master branch of the dummy repo which would result in lots of duplication of commits. The going assumption was that most branch commits eventually become master commits which would then get picked up by GitDummy.

I'm interested in re-visiting this though if it's practical and has some added benefit. Thoughts?

**Comment by brunolemos** [comment] 2015-09-14 16:30
Got it, didn't know it doesn't recognise non-master contributions!

I'm using one branch for the mobile version and another for the web version.
I believe the right approach is to use different repositories for this...

So no need to change gitdummy.
It could have a way to associate a branch to a different dummy repo, but not necessary, it might be over complicating it.

Thanks!

**Comment by ebrian** [comment] 2015-09-14 16:34
You could also maybe do:
```
your_repo/
    web/
    mobile/
```

On your second note "...have a way to associate a branch...", it *kinda* works like that right now in that if you are currently on a non-master branch, it will load the dummy repo out with that branch. You would just have to remember to switch branches first and that might be where the problem is.

**Comment by brunolemos** [comment] 2015-09-14 16:58
Cool, just did this:

````
folder_1
    branch: master
folder_2
    branch: web
````

It works.

**Comment by ebrian** [comment] 2015-09-14 17:00
Great. I'm gonna close this out until it makes sense to re-visit it :)

**Closed by ebrian** 2015-09-14 17:00 UTC
